services:
  - type: web
    name: disaster-response-backend
    runtime: node
    buildCommand: cd server && npm install
    startCommand: ./start.sh
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GOOGLE_MAPS_API_KEY
        sync: false 